kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: template-manager-role
rules:
  - verbs:
      - get
      - watch
      - list
      - create
    apiGroups:
      - template.openshift.io
    resources:
      - processedtemplates
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
    apiGroups:
      - serving.kserve.io
    resources:
      - servingruntimes
      - inferenceservices