kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: template-manager-rb
subjects:
  - kind: ServiceAccount
    name: pipeline-runner-dspa
    namespace: worldline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: template-manager-role