kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: worldline-demo-role
  namespace: worldline
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - patch
      - delete
    apiGroups:
      - template.openshift.io
    resources:
      - processedtemplates
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
    apiGroups:
      - serving.kserve.io
    resources:
      - servingruntimes
      - inferenceservices